import type { Category, PromptFormState } from "@/types/prompt";

export const BOTTOM_SAFE_AREA =
  "生成的每张图底部都额外多留出不少于 240px 的纯白色范围，或约占画面高度 12% 的底部安全留白区，用作后期放文字、排版或避免重要内容被底部平台信息遮挡；不要在这一区域放主体、注解、装饰元素或杂乱背景。";

export const defaultFormState: PromptFormState = {
  rawIdea: "",
  photoType: "日常照片",
  usageScene: "通用修图工具",
  keep: "",
  edit: "",
  subject: "",
  scene: "",
  actionRelation: "",
  mood: "",
  composition: "",
  aspectRatio: "",
  targetStyle: "",
  lighting: "",
  color: "",
  texture: "",
  quality: "",
  retouchStrength: "自然轻修",
  annotationObjects: "",
  annotationTextStyle: "",
  lineStyle: "",
  decorations: "",
  blankSpaceRule: "",
  negativePrompt: "",
  bottomSafeArea: BOTTOM_SAFE_AREA,
};

export const categories: Array<{
  id: Category;
  name: string;
  description: string;
  accent: string;
}> = [
  {
    id: "portrait",
    name: "人物照片轻修",
    description: "自拍、合照、头像、证件感轻修",
    accent: "bg-blue-50 text-blue-700",
  },
  {
    id: "lifestyle",
    name: "生活场景增强",
    description: "房间、咖啡馆、书桌、餐桌与日常空间",
    accent: "bg-amber-50 text-amber-700",
  },
  {
    id: "film",
    name: "胶片 / CCD / 氛围感",
    description: "复古颗粒、低饱和、生活抓拍感",
    accent: "bg-violet-50 text-violet-700",
  },
  {
    id: "note",
    name: "照片手账注解",
    description: "白色手绘线、箭头、小碎念文字",
    accent: "bg-rose-50 text-rose-700",
  },
  {
    id: "travel",
    name: "风景旅行",
    description: "城市、路牌、海边、山野、记忆感",
    accent: "bg-emerald-50 text-emerald-700",
  },
  {
    id: "pet_object",
    name: "宠物 / 小物件",
    description: "猫狗、玩偶、杯子、书、本子",
    accent: "bg-pink-50 text-pink-700",
  },
  {
    id: "cleanup",
    name: "背景清理 / 去杂物",
    description: "去杂物、补背景、改比例、留白",
    accent: "bg-sky-50 text-sky-700",
  },
  {
    id: "general",
    name: "通用修图增强",
    description: "自然、干净、真实的全局增强",
    accent: "bg-slate-100 text-slate-700",
  },
];

export const templateByCategory: Record<Category, Partial<PromptFormState>> = {
  portrait: {
    photoType: "人物照片",
    keep: "保留人物身份、五官特征、发型、服装、原始表情和真实光影",
    edit: "轻微提亮肤色，减少皮肤瑕疵，优化暗部，提升照片清晰度",
    targetStyle: "自然清透、真实照片感、轻微生活方式写真",
    mood: "舒服、干净、松弛",
    lighting: "柔和自然光，脸部不过曝，保留真实阴影",
    color: "低饱和暖白，肤色自然，不偏灰不偏黄",
    composition: "保留原构图，不裁切头发、手和身体关键部位",
    quality: "高清细节，自然锐化，保留皮肤纹理",
    retouchStrength: "自然轻修",
    negativePrompt:
      "不要改变人物长相，不要大眼瘦脸，不要过度磨皮，不要塑料皮肤，不要新增奇怪肢体和文字",
  },
  lifestyle: {
    photoType: "生活场景照片",
    keep: "保留原始空间结构、主要家具、物件位置、真实透视关系和生活痕迹",
    edit: "清理杂乱细节，提升光线层次，增强温暖生活氛围",
    targetStyle: "日系生活感、自然真实、干净温暖",
    mood: "安静、松弛、舒服",
    lighting: "柔和窗光，轻微暖光，阴影自然",
    color: "奶油色、木色、低饱和、干净白色",
    composition: "主体更突出，适当增加留白，不改变房间布局",
    texture: "真实材质、柔和纹理",
    quality: "高清自然，细节清楚，轻微胶片颗粒",
    negativePrompt: "不要改变空间结构，不要新增奇怪家具，不要过度 HDR，不要让画面像样板间",
  },
  film: {
    photoType: "旅行街拍或日常照片",
    keep: "保留原照片内容、人物真实特征、场景结构和自然曝光",
    edit: "增加轻微胶片颗粒、柔和对比、复古色偏、生活抓拍感",
    targetStyle: "胶片感、CCD感、低饱和、复古生活照",
    mood: "怀旧、松弛、随手记录感",
    lighting: "自然光或闪光灯直闪，保留真实阴影",
    color: "低饱和、轻微偏暖或偏青，黑位不死黑",
    texture: "胶片颗粒、轻微噪点",
    quality: "质感自然，颗粒细腻，清晰度不过度锐化",
    negativePrompt: "不要塑料感、不要过度锐化、不要过度噪点、不要脏黄、不要强烈 HDR",
  },
  note: {
    photoType: "餐桌/咖啡/甜品或日常照片",
    keep: "保留原照片构图、主体、真实光影和空白空间",
    edit: "添加白色手绘线条、物件轮廓描边、箭头或虚线引导、短句注解和少量可爱装饰",
    targetStyle: "手绘风注解、日系可爱手账、白色线稿、一笔画风格",
    mood: "日记感、小碎念、轻松、可爱但不油腻",
    lighting: "保留原照片光线，不额外改变照片主光源",
    color: "以白色手绘线为主，少量浅色小装饰，整体干净",
    composition: "注解围绕物件分布，保留空白，不遮挡主体和人物脸部",
    quality: "线条清晰但自然，不要机械感，文字可读",
    annotationObjects: "请先自动识别照片中的主要物件、空间元素和可注解的小细节",
    annotationTextStyle: "日系可爱手写风、小碎念，句子简短，带一点情绪",
    lineStyle: "白色细线、一笔画、随性不均匀、箭头或虚线引导",
    decorations: "爱心、星星、闪光、小表情、热气、虚线和圆圈，适度装饰",
    blankSpaceRule: "注解和装饰围绕主体分布，保留空白，不进入底部安全留白区",
    negativePrompt: "不要过度装饰、不要铺满画面、不要遮挡主体、不要生成乱码文字、不要改变原照片内容",
  },
  travel: {
    photoType: "风景旅行照片",
    keep: "保留旅行场景、人物或主体位置、城市/自然环境特征、真实光线和透视",
    edit: "增强旅行记忆感，优化天空、街景、色彩和画面层次",
    targetStyle: "旅行街拍、自然生活感、清爽干净、轻微胶片感",
    mood: "轻松、自然、记忆感",
    lighting: "晴天自然光、傍晚暖光，亮部不过曝",
    color: "清透、低饱和，天空和环境色自然",
    composition: "保留原始空间关系，增强层次，主体更突出",
    quality: "高清自然，纹理真实，远景不要糊成一片",
    negativePrompt: "不要过度换天，不要假 HDR，不要改变地标和人物特征，不要新增奇怪路人",
  },
  pet_object: {
    photoType: "宠物或小物件照片",
    keep: "保留宠物或物件的真实外形、表情、毛发/材质细节、原始光影",
    edit: "优化主体清晰度、背景干净度和可爱生活氛围",
    targetStyle: "自然可爱、生活随拍、干净柔和",
    mood: "可爱、生活感、轻松、治愈",
    lighting: "柔和自然光，毛发和材质保留层次",
    color: "柔和浅色、低饱和、主体颜色准确",
    texture: "真实、柔和，保留毛发或材质细节",
    quality: "高清细节，毛发/材质自然，不要糊边",
    negativePrompt: "不要改变主体形态，不要多生成肢体或物件，不要过度锐化，不要塑料质感",
  },
  cleanup: {
    photoType: "需要清理背景的照片",
    keep: "保留主体、人物身份、原始空间透视、光线方向和主要物件",
    edit: "去掉杂乱物品，补齐干净背景，增加适当留白",
    targetStyle: "自然修复、干净真实、无痕迹",
    mood: "简洁、舒服",
    lighting: "匹配原图光线方向和阴影",
    color: "匹配原图色彩，不突兀",
    composition: "保持主体位置，背景补全自然，不拉伸变形",
    quality: "修复区域纹理自然，边缘干净",
    negativePrompt: "不要改变主体，不要生成重复纹理，不要拉伸背景，不要新增奇怪物体，不要破坏透视",
  },
  general: {
    photoType: "日常照片",
    keep: "保留原照片主体、真实光影、空间关系和照片感",
    edit: "提升清晰度、光线层次、色彩干净度和整体完成度",
    targetStyle: "自然真实、干净、轻微高级感",
    mood: "轻松、好看、日常记录感",
    lighting: "柔和自然光，画面通透不过曝",
    color: "干净明亮、低饱和、肤色和环境色自然",
    composition: "主体突出，适当留白，保持原始空间关系",
    quality: "高清自然，细节清楚，少一点 AI 味",
    negativePrompt: "不要过度滤镜，不要文字乱码，不要装饰过满，不要改变真实主体",
  },
};

export const fieldLabels: Record<keyof PromptFormState, string> = {
  rawIdea: "原始想法",
  photoType: "照片类型",
  usageScene: "使用场景",
  keep: "保留内容",
  edit: "修改方向",
  subject: "主体",
  scene: "场景",
  actionRelation: "动作 / 关系",
  mood: "氛围",
  composition: "构图",
  aspectRatio: "画面比例",
  targetStyle: "目标风格",
  lighting: "光线",
  color: "色彩",
  texture: "质感",
  quality: "画质",
  retouchStrength: "修图强度",
  annotationObjects: "注解对象",
  annotationTextStyle: "注解文字风格",
  lineStyle: "线条风格",
  decorations: "装饰元素",
  blankSpaceRule: "注解留白规则",
  negativePrompt: "禁止项",
  bottomSafeArea: "底部安全留白",
};
