import type { Category, PromptFormState } from "@/types/prompt";

export const BOTTOM_SAFE_AREA =
  "生成的每张图底部都额外多留出不少于 240px 的纯白色范围，或约占画面高度 12% 的底部安全留白区，用作后期放文字、排版或避免重要内容被底部平台信息遮挡；不要在这一区域放主体、注解、装饰元素或杂乱背景。";

export const defaultFormState: PromptFormState = {
  rawIdea: "",
  photoType: "日常照片",
  usageScene: "通用修图工具",
  keep: "",
  edit: "",
  subject: "",
  scene: "",
  actionRelation: "",
  mood: "",
  composition: "",
  aspectRatio: "",
  targetStyle: "",
  lighting: "",
  color: "",
  texture: "",
  quality: "",
  retouchStrength: "自然轻修",
  annotationObjects: "",
  annotationTextStyle: "",
  lineStyle: "",
  decorations: "",
  blankSpaceRule: "",
  negativePrompt: "",
  bottomSafeArea: BOTTOM_SAFE_AREA,
};

export const categories: Array<{
  id: Category;
  name: string;
  description: string;
  accent: string;
}> = [
  {
    id: "portrait",
    name: "人像变好看",
    description: "自拍、合照、头像，自然干净不网红",
    accent: "bg-blue-50 text-blue-700",
  },
  {
    id: "lifestyle",
    name: "日常变干净",
    description: "房间、咖啡馆、书桌、餐桌更舒服",
    accent: "bg-amber-50 text-amber-700",
  },
  {
    id: "film",
    name: "胶片氛围感",
    description: "复古颗粒、低饱和、随手拍感觉",
    accent: "bg-violet-50 text-violet-700",
  },
  {
    id: "travel",
    name: "旅行更出片",
    description: "城市、路牌、海边、山野、记忆感",
    accent: "bg-emerald-50 text-emerald-700",
  },
  {
    id: "pet_object",
    name: "小物更可爱",
    description: "宠物、玩偶、杯子、书、本子",
    accent: "bg-pink-50 text-pink-700",
  },
  {
    id: "cleanup",
    name: "去掉杂物",
    description: "清理背景、补空白、改比例、留白",
    accent: "bg-sky-50 text-sky-700",
  },
  {
    id: "general",
    name: "我也说不清",
    description: "先帮我变自然、干净、好看",
    accent: "bg-slate-100 text-slate-700",
  },
];

export const templateByCategory: Record<Category, Partial<PromptFormState>> = {
  portrait: {
    photoType: "人物照片",
    keep: "保留人物身份、五官特征、发型、服装、原始表情和真实光影",
    edit: "轻微提亮肤色，减少皮肤瑕疵，优化暗部，提升照片清晰度",
    targetStyle: "自然清透、真实照片感、轻微生活方式写真",
    mood: "舒服、干净、松弛",
    lighting: "柔和自然光，脸部不过曝，保留真实阴影",
    color: "低饱和暖白，肤色自然，不偏灰不偏黄",
    composition: "保留原构图，不裁切头发、手和身体关键部位",
    quality: "高清细节，自然锐化，保留皮肤纹理",
    retouchStrength: "自然轻修",
    negativePrompt:
      "不要改变人物长相，不要大眼瘦脸，不要过度磨皮，不要塑料皮肤，不要新增奇怪肢体和文字",
  },
  lifestyle: {
    photoType: "生活场景照片",
    keep: "保留原始空间结构、主要家具、物件位置、真实透视关系和生活痕迹",
    edit: "清理杂乱细节，提升光线层次，增强温暖生活氛围",
    targetStyle: "日系生活感、自然真实、干净温暖",
    mood: "安静、松弛、舒服",
    lighting: "柔和窗光，轻微暖光，阴影自然",
    color: "奶油色、木色、低饱和、干净白色",
    composition: "主体更突出，适当增加留白，不改变房间布局",
    texture: "真实材质、柔和纹理",
    quality: "高清自然，细节清楚，轻微胶片颗粒",
    negativePrompt: "不要改变空间结构，不要新增奇怪家具，不要过度 HDR，不要让画面像样板间",
  },
  film: {
    photoType: "旅行街拍或日常照片",
    keep: "保留原照片内容、人物真实特征、场景结构和自然曝光",
    edit: "增加轻微胶片颗粒、柔和对比、复古色偏、生活抓拍感",
    targetStyle: "胶片感、CCD感、低饱和、复古生活照",
    mood: "怀旧、松弛、随手记录感",
    lighting: "自然光或闪光灯直闪，保留真实阴影",
    color: "低饱和、轻微偏暖或偏青，黑位不死黑",
    texture: "胶片颗粒、轻微噪点",
    quality: "质感自然，颗粒细腻，清晰度不过度锐化",
    negativePrompt: "不要塑料感、不要过度锐化、不要过度噪点、不要脏黄、不要强烈 HDR",
  },
  note: {
    photoType: "餐桌/咖啡/甜品或日常照片",
    keep: "保留原照片构图、主体、真实光影和空白空间",
    edit: "添加白色手绘线条、物件轮廓描边、箭头或虚线引导、短句注解和少量可爱装饰",
    targetStyle: "手绘风注解、日系可爱手账、白色线稿、一笔画风格",
    mood: "日记感、小碎念、轻松、可爱但不油腻",
    lighting: "保留原照片光线，不额外改变照片主光源",
    color: "以白色手绘线为主，少量浅色小装饰，整体干净",
    composition: "注解围绕物件分布，保留空白，不遮挡主体和人物脸部",
    quality: "线条清晰但自然，不要机械感，文字可读",
    annotationObjects: "请先自动识别照片中的主要物件、空间元素和可注解的小细节",
    annotationTextStyle: "日系可爱手写风、小碎念，句子简短，带一点情绪",
    lineStyle: "白色细线、一笔画、随性不均匀、箭头或虚线引导",
    decorations: "爱心、星星、闪光、小表情、热气、虚线和圆圈，适度装饰",
    blankSpaceRule: "注解和装饰围绕主体分布，保留空白，不进入底部安全留白区",
    negativePrompt: "不要过度装饰、不要铺满画面、不要遮挡主体、不要生成乱码文字、不要改变原照片内容",
  },
  travel: {
    photoType: "风景旅行照片",
    keep: "保留旅行场景、人物或主体位置、城市/自然环境特征、真实光线和透视",
    edit: "增强旅行记忆感，优化天空、街景、色彩和画面层次",
    targetStyle: "旅行街拍、自然生活感、清爽干净、轻微胶片感",
    mood: "轻松、自然、记忆感",
    lighting: "晴天自然光、傍晚暖光，亮部不过曝",
    color: "清透、低饱和，天空和环境色自然",
    composition: "保留原始空间关系，增强层次，主体更突出",
    quality: "高清自然，纹理真实，远景不要糊成一片",
    negativePrompt: "不要过度换天，不要假 HDR，不要改变地标和人物特征，不要新增奇怪路人",
  },
  pet_object: {
    photoType: "宠物或小物件照片",
    keep: "保留宠物或物件的真实外形、表情、毛发/材质细节、原始光影",
    edit: "优化主体清晰度、背景干净度和可爱生活氛围",
    targetStyle: "自然可爱、生活随拍、干净柔和",
    mood: "可爱、生活感、轻松、治愈",
    lighting: "柔和自然光，毛发和材质保留层次",
    color: "柔和浅色、低饱和、主体颜色准确",
    texture: "真实、柔和，保留毛发或材质细节",
    quality: "高清细节，毛发/材质自然，不要糊边",
    negativePrompt: "不要改变主体形态，不要多生成肢体或物件，不要过度锐化，不要塑料质感",
  },
  cleanup: {
    photoType: "需要清理背景的照片",
    keep: "保留主体、人物身份、原始空间透视、光线方向和主要物件",
    edit: "去掉杂乱物品，补齐干净背景，增加适当留白",
    targetStyle: "自然修复、干净真实、无痕迹",
    mood: "简洁、舒服",
    lighting: "匹配原图光线方向和阴影",
    color: "匹配原图色彩，不突兀",
    composition: "保持主体位置，背景补全自然，不拉伸变形",
    quality: "修复区域纹理自然，边缘干净",
    negativePrompt: "不要改变主体，不要生成重复纹理，不要拉伸背景，不要新增奇怪物体，不要破坏透视",
  },
  doodle_snap: {
    photoType: "真实手持手机随拍快照",
    usageScene: "社交媒体故事批注、学生日记、杂志标记风格",
    keep: "保留真实手持手机随拍质感，场景可为校园、画廊、工作室、咖啡馆、夜市或街头；保留墙面艺术、标签、海报、货架、桌子、灯具、书籍、展示板、人群、织物、阴影、噪点、轻微模糊和不完美曝光",
    edit: "在照片上叠加非常强烈、密集、混乱的数字马克笔涂鸦；主体轮廓用亮粉色粗线勾勒，带青色偏移线条或光晕；主体周围向外放射黄橙尖刺、角、射线、鳍状物、太阳光芒般怪物形态；画面留白和四周加入大量粗糙手写文字，包括大标题、情绪标语、重复词、短笑话、日期标签、学习批注",
    subject: "学生、艺术家、朋友或安静路人，背影或四分之三侧面，可拿笔记本、帆布袋、咖啡、手机、速写本等道具",
    scene: "校园、画廊、工作室、咖啡馆、夜市或街头",
    actionRelation: "正在看展、学习、走路、等待、浏览或拿着日常道具",
    targetStyle: "真实手持手机随拍快照风格、学生日记、杂志标记、社交媒体故事批注感、霓虹混乱密集夸张涂鸦覆盖",
    mood: "俏皮、青春、走神、有点过度刺激、亲切又有个性",
    lighting: "保留现场光和不完美曝光，可有噪点、轻微模糊、阴影和手机快照感",
    color: "亮粉色主体粗线、青色偏移线条或光晕、黄橙色尖刺射线、霓虹高对比涂鸦",
    texture: "粗厚数字马克笔、摇晃黑色轮廓、粗糙笔刷边缘、随意压力变化",
    composition: "整体略微倾斜、不完美构图，主体位于画面中心或偏右；涂鸦层明显覆盖照片上方，可遮挡部分人物和物体，但底图仍清晰",
    quality: "底图保持真实快照清晰度，允许噪点、轻微糊、曝光不完美；涂鸦边缘粗糙有手写感",
    annotationObjects: "主体轮廓、周围空间、墙面艺术、海报、标签、桌面物件、人群和道具",
    annotationTextStyle: "大量粗糙手写文字，大标题、情绪标语、重复词、短笑话、日期标签、学习批注，像学生日记和社交媒体故事涂写",
    lineStyle: "粗厚数字马克笔线条、亮粉色粗描边、青色偏移线条、摇晃黑色轮廓、随意压力变化",
    decorations: "星星、爪印、蜘蛛网边角、光环、抽象眼睛、植物、花朵、爱心、箭头、计数符号、下划线、涂鸦条、黄橙尖刺和太阳光芒怪物形态",
    blankSpaceRule: "四周和留白处允许密集文字与符号，但底部安全留白区仍需保留给后期排版",
    retouchStrength: "明显风格化",
    negativePrompt: "不要做成干净极简风，不要只有少量装饰，不要柔和淡雅，不要把底图完全盖住，不要生成乱码文字，不要让主体完全不可辨认",
  },
  general: {
    photoType: "日常照片",
    keep: "保留原照片主体、真实光影、空间关系和照片感",
    edit: "提升清晰度、光线层次、色彩干净度和整体完成度",
    targetStyle: "自然真实、干净、轻微高级感",
    mood: "轻松、好看、日常记录感",
    lighting: "柔和自然光，画面通透不过曝",
    color: "干净明亮、低饱和、肤色和环境色自然",
    composition: "主体突出，适当留白，保持原始空间关系",
    quality: "高清自然，细节清楚，少一点 AI 味",
    negativePrompt: "不要过度滤镜，不要文字乱码，不要装饰过满，不要改变真实主体",
  },
};

export type TrendTemplate = {
  id: string;
  category: Category;
  name: string;
  tag: string;
  description: string;
  rawIdea: string;
  form: Partial<PromptFormState>;
};

export const trendTemplates: TrendTemplate[] = [
  {
    id: "note",
    category: "note",
    name: "手账碎碎念",
    tag: "可爱注解",
    description: "白色线条、小箭头、小字批注，适合咖啡、餐桌、日常照片。",
    rawIdea: "咖啡店或餐桌照片加白色手账小字，保留原图氛围，底部留白方便放文字",
    form: {
      ...templateByCategory.note,
      rawIdea: "咖啡店或餐桌照片加白色手账小字，保留原图氛围，底部留白方便放文字",
      edit: "添加白色手绘线条、物件轮廓描边、箭头或虚线引导、短句小碎念注解和少量可爱装饰；保留原图氛围，底部留白方便后期排版",
      mood: "日记感、小碎念、轻松、可爱但不幼稚",
      color: "以白色手绘线为主，少量奶油色、浅粉或浅蓝点缀，整体温柔干净",
      blankSpaceRule: "注解和装饰围绕主体分布，保留空白，不进入底部安全留白区",
    },
  },
  {
    id: "doodle_snap",
    category: "doodle_snap",
    name: "涂鸦快照风",
    tag: "高能出片",
    description: "霓虹马克笔、密集涂鸦、杂志标记感，适合做社交平台故事图。",
    rawIdea: "真实手机随拍，加霓虹马克笔涂鸦，密集混乱一点，像学生日记和杂志标记",
    form: {
      ...templateByCategory.doodle_snap,
      rawIdea: "真实手机随拍，加霓虹马克笔涂鸦，密集混乱一点，像学生日记和杂志标记",
      edit: "叠加高能、密集、混乱的数字马克笔涂鸦；用亮粉色粗线圈出主体，加入青色偏移、黄橙尖刺、手写大字、星星、箭头、爪印、蜘蛛网和涂鸦条，像社交媒体故事批注",
      mood: "青春、俏皮、夸张、密集、有一点过度刺激但很好玩",
      color: "亮粉色、青色偏移、黄橙尖刺、黑色摇晃轮廓和霓虹高对比点缀",
      negativePrompt: "不要做成干净极简风，不要只有少量装饰，不要把底图完全盖住，不要生成乱码文字，不要让主体完全不可辨认",
    },
  },
  {
    id: "film",
    category: "film",
    name: "低饱和胶片",
    tag: "松弛氛围",
    description: "轻颗粒、低对比、随手拍感，适合街拍、旅行和生活记录。",
    rawIdea: "旅行街拍调成低饱和胶片感，有一点随手拍颗粒，松弛自然",
    form: {
      ...templateByCategory.film,
      rawIdea: "旅行街拍调成低饱和胶片感，有一点随手拍颗粒，松弛自然",
      edit: "加入低饱和胶片色调、轻微颗粒、柔和对比和随手拍氛围；保留真实曝光和人物特征",
      targetStyle: "低饱和胶片感、CCD随手拍、复古生活照、轻颗粒",
      mood: "松弛、怀旧、自然、不刻意摆拍",
      color: "低饱和、轻微偏暖或偏青，黑位不死黑，高光柔和不过曝",
      negativePrompt: "不要过度锐化，不要强 HDR，不要脏黄，不要滤镜太重，不要塑料感",
    },
  },
  {
    id: "lifestyle",
    category: "lifestyle",
    name: "奶油生活感",
    tag: "温柔干净",
    description: "暖白、奶油色、窗边自然光，适合房间、咖啡馆和书桌。",
    rawIdea: "房间或咖啡馆照片变成奶油生活感，温柔干净，保留生活痕迹",
    form: {
      ...templateByCategory.lifestyle,
      rawIdea: "房间或咖啡馆照片变成奶油生活感，温柔干净，保留生活痕迹",
      edit: "把画面整理得更干净温柔，增加奶油色和暖白生活感，清理明显杂乱但保留真实生活痕迹",
      targetStyle: "奶油生活感、温柔干净、日系自然、轻微胶片颗粒",
      lighting: "柔和窗边自然光，轻微暖光，阴影自然不过重",
      color: "奶油色、暖白、浅木色、低饱和柔和色彩",
      negativePrompt: "不要变成样板间，不要过度磨平质感，不要新增奇怪家具，不要过度 HDR",
    },
  },
];

export const ideaExamples = [
  "自拍修自然一点，皮肤干净但保留真实纹理，不要网红脸",
  "咖啡店照片加白色手账小字，保留原图氛围，底部留白",
  "旅行街拍调成胶片感，低饱和，有一点随手拍颗粒",
  "真实手机随拍，加霓虹马克笔涂鸦，密集混乱一点",
  "房间照片变干净温暖，保留生活痕迹，不要像样板间",
  "餐桌照片加白色线条注解，小碎念文字，画面不要太满",
  "去掉背景杂物，补齐干净墙面，主体位置不要改变",
  "小物照片更可爱，奶油色，柔和自然光，细节清楚",
];

export const fieldLabels: Record<keyof PromptFormState, string> = {
  rawIdea: "原始想法",
  photoType: "照片类型",
  usageScene: "使用场景",
  keep: "保留内容",
  edit: "修改方向",
  subject: "主体",
  scene: "场景",
  actionRelation: "动作 / 关系",
  mood: "氛围",
  composition: "构图",
  aspectRatio: "画面比例",
  targetStyle: "目标风格",
  lighting: "光线",
  color: "色彩",
  texture: "质感",
  quality: "画质",
  retouchStrength: "修图强度",
  annotationObjects: "注解对象",
  annotationTextStyle: "注解文字风格",
  lineStyle: "线条风格",
  decorations: "装饰元素",
  blankSpaceRule: "注解留白规则",
  negativePrompt: "禁止项",
  bottomSafeArea: "底部安全留白",
};
